= A Note to Readers & Contributors

There is no sense in postponing your realization: I have written a user manual for the role of tech writer.
The first draft of that sentence originally contained a reference to _irony_, but in truth it is not at all ironic that technical writers themselves require instruction.
I've strung together a lot of prose in my lifetime, but I'm handling this book project with a type of concision I hope technical writers and software developers will appreciate:
lots of bulleted section headings, lists, sidebars, examples, code listings, and summaries--not a lot of rants.

[[tech-writer-journalist]]
[TIP]
.A tech writer is not a tech journalist
*Tech writers* _document and instruct_ a product on behalf of its _makers_ (usually _as one of its makers_).
By contrast, *tech journalists* _promote and praise_ products on behalf of the journalists' _sponsors_, which are often those same products. Uncoincidentally.

I don't want you to just read this book; I want you to contribute to it.

== Collaborative Authoring

_Code Writing_ is a living document being written on a public GitHub repository.
You are welcome and encouraged to contribute by forking the repo, contributing edits, and issuing a pull request (PR).
For detailed instructions, see <<appendix-contributing>>.

Be sure to add your name to the contributors list with your PR!

== Writing to Learn

Every subject in which I have achieved true proficiency, I have written about.
But I do not write as an expert, conveying my accumulated wisdom;
as a former journalist, I write to motivate and structure research efforts during the intermediate part of a learning project
If I knew everything I need to know to master tech writing and DocOps, I would not be writing this book.

[WARNING]
"Intermediate" may best describe my proficiency at technical writing, and then only because I join the field with nearly 20 years in software development and even longer writing professionally.
I won't release editions of this book that contain known falsehoods, but it may always contain a significant amount of vagueries and shortfalls.
The main challenge is to

== Engaged Learning

As a technical writer, I like to use examples.
I also happen to learn best from examples.
Most importantly, I learn best by following along.

For these reasons, a narrative structure will be threaded throughout the book, and you are encouraged to play along.
All the tools you will need are introduced as they are called for.
Every tool used in these instructions will be free and open source software.
Examples in this book heavily favor AsciiDoc markup language, though I have used Markdown and reStructuredText occasionally as well.
The particular language should not matter for most examples, however.

== Tech Writing Can Be Fun & Funny

I'm enjoying this book, but I have to admit, the Reference Guide I maintain as the primary responsibility of my day job is not always a page-turner (for reading or writing).
I get enjoyment out of many of the non-writing parts of this job, including working with great developers and getting my hands dirty with their bleeding-edge software.
Still, we all know tech writing can be the opposite of pleasure writing.
Fussing over every word in an instruction step, trying to shorten code listing line lengths to fit the page, or just re-conveying the same banal concepts over and over; tech writing has its downsides.

Consider this: customers pay _seven figures_ for our product license, and the only physical artifact of the product itself that any of them will ever touch will pass across my desk first.
It has been conveyed to be by people of good repute that joking and cursing in technical documentation for a "serious" enterprise product is a bad move.

I would like to propose a compromise.

I will bite my tongue on the F-bombs, S-storms, and D-words, but let's try to inject humor into this most dry of _crafts_.
It may never rise to the level of an _art form_, but I'll take _craftsperson_ over _clerk_ as a category any day.

Also, _shitfuck_. There, I had to do one; now I'm going back to the moratorium I offered.

[NOTE]
If at this point you are wishing I had chosen cursing over humor, you are likely not alone.

== Creative Commons License

I'm not trying to get rich or famous off this book (if that was not already obvious, you might be in the wrong place; _try <<tech-writer-journalist,tech journalism>>_).
You can take this text and do what you want with it, so long as you leave a cookie trail of credit as described in the <<creative-commons,copyright and licensing notice>>.

I would be honored if a free-thinking colleague ever decided to fork this, whether to contribute substantively and propose a re-merge, or to take this idea in another direction--_so long as you promise to freely share the results_.

See the rules in <<creative-commons>>.
